default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  database: cache
  <<: *default

test:
  database: cache
  <<: *default

production:
  # Don't specify database - will use ActiveRecord::Base connection (same DB as primary)
  # This is required when using a single PostgreSQL database on Render
  <<: *default
  store_options:
    max_age: <%= 60.days.to_i %>
    max_size: <%= 1.gigabyte %>
    namespace: <%= Rails.env %>
